# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-23 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='last_user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile'),
        ),
    ]
