# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-23 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180223_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='review_cycle',
            field=models.CharField(blank=True, choices=[('yearly', 'Yearly'), ('quarterly', 'Quarterly'), ('monthly', 'Monthly'), ('weekly', 'Weekly')], max_length=255, null=True),
        ),
    ]
