# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-23 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180223_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='next_review_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
